"""Operator commands for the bench adoption service."""

from __future__ import annotations

import argparse
import os
from random import Random
from typing import Any

from psycopg import Connection, Cursor

from .domain import generate_initial_adoption_timelines, park_today
from .locations import generated_bench_coordinates
from .postgres import connect


SCHEMA = """
CREATE TABLE IF NOT EXISTS benches (
    id TEXT PRIMARY KEY,
    location TEXT NOT NULL,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL
);
ALTER TABLE benches ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION;
ALTER TABLE benches ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION;
CREATE TABLE IF NOT EXISTS adopters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_name TEXT NOT NULL CHECK (length(trim(public_name)) BETWEEN 1 AND 80)
);
CREATE TABLE IF NOT EXISTS adoptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bench_id TEXT NOT NULL REFERENCES benches(id),
    adopter_id BIGINT NOT NULL REFERENCES adopters(id),
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    amount_cents BIGINT NOT NULL CHECK (amount_cents > 0),
    CHECK (end_date > start_date)
);
CREATE INDEX IF NOT EXISTS adoptions_bench_dates
    ON adoptions (bench_id, end_date, start_date);
"""


def migrate(connection: Connection[dict[str, Any]]) -> None:
    """Create the hosted schema and backfill stable prototype coordinates."""
    with connection.transaction():
        with connection.cursor() as cursor:
            for statement in SCHEMA.split(";"):
                if statement.strip():
                    cursor.execute(statement)
            cursor.execute(
                "SELECT id FROM benches WHERE latitude IS NULL OR longitude IS NULL"
            )
            updates = []
            for row in cursor.fetchall():
                number = int(row["id"].removeprefix("Bench"))
                latitude, longitude = generated_bench_coordinates(number)
                updates.append((latitude, longitude, row["id"]))
            if updates:
                cursor.executemany(
                    "UPDATE benches SET latitude = %s, longitude = %s WHERE id = %s",
                    updates,
                )
            cursor.execute("ALTER TABLE benches ALTER COLUMN latitude SET NOT NULL")
            cursor.execute("ALTER TABLE benches ALTER COLUMN longitude SET NOT NULL")


def _seed_in_transaction(
    cursor: Cursor[dict[str, Any]], *, randomizer: Random | None = None,
) -> None:
    cursor.execute("SELECT COUNT(*) AS count FROM benches")
    if cursor.fetchone()["count"]:
        return
    benches = []
    for number in range(1, 551):
        latitude, longitude = generated_bench_coordinates(number)
        benches.append(
            (
                f"Bench{number}",
                f"Park Area {(number - 1) // 50 + 1} · Site {(number - 1) % 50 + 1}",
                latitude,
                longitude,
            )
        )
    cursor.executemany(
        "INSERT INTO benches (id, location, latitude, longitude) VALUES (%s, %s, %s, %s)",
        benches,
    )
    today = park_today()
    for number, start, end in generate_initial_adoption_timelines(
        today=today, randomizer=randomizer
    ):
        cursor.execute(
            "INSERT INTO adopters (public_name) VALUES (%s) RETURNING id",
            ("Anonymous Park Supporter",),
        )
        adopter_id = cursor.fetchone()["id"]
        cursor.execute(
            """INSERT INTO adoptions
               (bench_id, adopter_id, start_date, end_date, amount_cents)
               VALUES (%s, %s, %s, %s, %s)""",
            (f"Bench{number}", adopter_id, start, end, 10000),
        )


def seed(
    connection: Connection[dict[str, Any]], *, randomizer: Random | None = None,
) -> None:
    """Add the initial inventory once; repeat calls do nothing."""
    with connection.transaction():
        with connection.cursor() as cursor:
            cursor.execute("LOCK TABLE benches IN ACCESS EXCLUSIVE MODE")
            _seed_in_transaction(cursor, randomizer=randomizer)


def _initial_adoption_rows(
    cursor: Cursor[dict[str, Any]],
) -> list[dict[str, Any]]:
    expected_benches = {f"Bench{number}" for number in range(1, 31)}
    cursor.execute(
        """SELECT a.id, a.bench_id, a.adopter_id, p.public_name
           FROM adoptions a
           JOIN adopters p ON p.id = a.adopter_id
           WHERE a.bench_id = ANY(%s)
             AND a.amount_cents = 10000
             AND (p.public_name = 'Anonymous Park Supporter'
                  OR p.public_name ~ '^Demo Donor ([1-9]|[12][0-9]|30)$')
           FOR UPDATE OF a, p""",
        (sorted(expected_benches),),
    )
    rows = cursor.fetchall()
    if len(rows) != 30 or {row["bench_id"] for row in rows} != expected_benches:
        raise RuntimeError(
            "Expected exactly the 30 initial adoptions; no records changed."
        )
    return rows


def refresh_timelines(
    connection: Connection[dict[str, Any]], *, randomizer: Random | None = None,
) -> int:
    """Refresh the 30 initial timelines while preserving visitor bookings."""
    with connection.transaction():
        with connection.cursor() as cursor:
            adoption_ids = {
                row["bench_id"]: row["id"] for row in _initial_adoption_rows(cursor)
            }
            for number, start, end in generate_initial_adoption_timelines(
                today=park_today(), randomizer=randomizer
            ):
                cursor.execute(
                    "UPDATE adoptions SET start_date = %s, end_date = %s WHERE id = %s",
                    (start, end, adoption_ids[f"Bench{number}"]),
                )
    return 30


def normalize_content(connection: Connection[dict[str, Any]]) -> int:
    """Replace legacy placeholder labels without touching visitor-created records."""
    with connection.transaction():
        with connection.cursor() as cursor:
            initial_rows = _initial_adoption_rows(cursor)
            for number in range(1, 551):
                cursor.execute(
                    """UPDATE benches SET location = %s
                       WHERE id = %s AND location LIKE 'Demo Zone %%'""",
                    (
                        f"Park Area {(number - 1) // 50 + 1} · Site {(number - 1) % 50 + 1}",
                        f"Bench{number}",
                    ),
                )
            cursor.execute(
                "UPDATE adopters SET public_name = 'Anonymous Park Supporter' WHERE id = ANY(%s)",
                ([row["adopter_id"] for row in initial_rows],),
            )
    return 580


def reset(
    connection: Connection[dict[str, Any]], *, randomizer: Random | None = None,
) -> None:
    """Erase all bookings and restore the initial state atomically."""
    with connection.transaction():
        with connection.cursor() as cursor:
            cursor.execute("LOCK TABLE benches, adopters, adoptions IN ACCESS EXCLUSIVE MODE")
            cursor.execute("DELETE FROM adoptions")
            cursor.execute("DELETE FROM adopters")
            cursor.execute("DELETE FROM benches")
            _seed_in_transaction(cursor, randomizer=randomizer)


def main() -> None:
    """Run a migration, seed, or explicit operator reset."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "command", choices=("migrate", "seed", "refresh-timelines", "normalize-content", "reset")
    )
    parser.add_argument("--yes", action="store_true", help="Confirm the destructive reset")
    args = parser.parse_args()
    if args.command == "reset" and not args.yes:
        parser.error("reset removes all bookings; pass --yes to confirm")
    database_url = os.environ.get("DATABASE_URL")
    if not database_url:
        parser.error("DATABASE_URL is required")
    with connect(database_url) as connection:
        {
            "migrate": migrate,
            "seed": seed,
            "refresh-timelines": refresh_timelines,
            "normalize-content": normalize_content,
            "reset": reset,
        }[args.command](connection)
    print(f"{args.command} complete")


if __name__ == "__main__":
    main()
