"""Operator commands for the hosted Postgres demo."""

from __future__ import annotations

import argparse
import os
from random import Random
from typing import Any

from psycopg import Connection, Cursor

from .domain import generate_seed_adoption_timelines, park_today
from .postgres import connect


SCHEMA = """
CREATE TABLE IF NOT EXISTS benches (
    id TEXT PRIMARY KEY,
    location TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS adopters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_name TEXT NOT NULL CHECK (length(trim(public_name)) BETWEEN 1 AND 80)
);
CREATE TABLE IF NOT EXISTS adoptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bench_id TEXT NOT NULL REFERENCES benches(id),
    adopter_id BIGINT NOT NULL REFERENCES adopters(id),
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    amount_cents BIGINT NOT NULL CHECK (amount_cents > 0),
    CHECK (end_date > start_date)
);
CREATE INDEX IF NOT EXISTS adoptions_bench_dates
    ON adoptions (bench_id, end_date, start_date);
"""


def migrate(connection: Connection[dict[str, Any]]) -> None:
    """Create the hosted schema without changing existing records."""
    with connection.transaction():
        with connection.cursor() as cursor:
            for statement in SCHEMA.split(";"):
                if statement.strip():
                    cursor.execute(statement)


def _seed_in_transaction(
    cursor: Cursor[dict[str, Any]], *, randomizer: Random | None = None,
) -> None:
    cursor.execute("SELECT COUNT(*) AS count FROM benches")
    if cursor.fetchone()["count"]:
        return
    benches = [
        (f"Bench{number}", f"Demo Zone {(number - 1) // 50 + 1} · Spot {(number - 1) % 50 + 1}")
        for number in range(1, 551)
    ]
    cursor.executemany("INSERT INTO benches (id, location) VALUES (%s, %s)", benches)
    today = park_today()
    for number, start, end in generate_seed_adoption_timelines(
        today=today, randomizer=randomizer
    ):
        cursor.execute(
            "INSERT INTO adopters (public_name) VALUES (%s) RETURNING id",
            (f"Demo Donor {number}",),
        )
        adopter_id = cursor.fetchone()["id"]
        cursor.execute(
            """INSERT INTO adoptions
               (bench_id, adopter_id, start_date, end_date, amount_cents)
               VALUES (%s, %s, %s, %s, %s)""",
            (f"Bench{number}", adopter_id, start, end, 10000),
        )


def seed(
    connection: Connection[dict[str, Any]], *, randomizer: Random | None = None,
) -> None:
    """Add the fictional inventory once; repeat calls do nothing."""
    with connection.transaction():
        with connection.cursor() as cursor:
            cursor.execute("LOCK TABLE benches IN ACCESS EXCLUSIVE MODE")
            _seed_in_transaction(cursor, randomizer=randomizer)


def reset(
    connection: Connection[dict[str, Any]], *, randomizer: Random | None = None,
) -> None:
    """Erase demo bookings and restore the fictional starting state atomically."""
    with connection.transaction():
        with connection.cursor() as cursor:
            cursor.execute("LOCK TABLE benches, adopters, adoptions IN ACCESS EXCLUSIVE MODE")
            cursor.execute("DELETE FROM adoptions")
            cursor.execute("DELETE FROM adopters")
            cursor.execute("DELETE FROM benches")
            _seed_in_transaction(cursor, randomizer=randomizer)


def main() -> None:
    """Run a migration, seed, or explicit operator reset."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=("migrate", "seed", "reset"))
    parser.add_argument("--yes", action="store_true", help="Confirm the destructive reset")
    args = parser.parse_args()
    if args.command == "reset" and not args.yes:
        parser.error("reset removes all bookings; pass --yes to confirm")
    database_url = os.environ.get("DATABASE_URL")
    if not database_url:
        parser.error("DATABASE_URL is required")
    with connect(database_url) as connection:
        {"migrate": migrate, "seed": seed, "reset": reset}[args.command](connection)
    print(f"{args.command} complete")


if __name__ == "__main__":
    main()
