"""Operator commands for the bench adoption service."""

from __future__ import annotations

import argparse
import os
from random import Random
from typing import Any

from psycopg import Connection, Cursor

from .domain import (
    DAILY_ADOPTION_RATE_CENTS,
    INITIAL_ADOPTION_COUNT,
    generated_adopter_name,
    generate_initial_adoption_timelines,
    park_today,
)
from .locations import generated_bench_coordinates, generated_bench_location
from .postgres import connect


SCHEMA = f"""
CREATE TABLE IF NOT EXISTS benches (
    id TEXT PRIMARY KEY,
    location TEXT NOT NULL,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL
);
ALTER TABLE benches ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION;
ALTER TABLE benches ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION;
CREATE TABLE IF NOT EXISTS adopters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_name TEXT NOT NULL CHECK (length(trim(public_name)) BETWEEN 1 AND 80)
);
CREATE TABLE IF NOT EXISTS adoptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bench_id TEXT NOT NULL REFERENCES benches(id),
    adopter_id BIGINT NOT NULL REFERENCES adopters(id),
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    amount_cents BIGINT NOT NULL CHECK (amount_cents > 0),
    is_seeded BOOLEAN NOT NULL DEFAULT FALSE,
    CHECK (end_date > start_date)
);
ALTER TABLE adoptions ADD COLUMN IF NOT EXISTS is_seeded BOOLEAN NOT NULL DEFAULT FALSE;
UPDATE adoptions a SET is_seeded = TRUE
FROM adopters p
WHERE a.adopter_id = p.id
  AND a.amount_cents = 10000
  AND (p.public_name = 'Anonymous Park Supporter'
       OR p.public_name ~ '^Demo Donor [1-9][0-9]*$');
UPDATE adoptions
SET amount_cents = (end_date - start_date + 1) * {DAILY_ADOPTION_RATE_CENTS}
WHERE is_seeded;
CREATE INDEX IF NOT EXISTS adoptions_bench_dates
    ON adoptions (bench_id, end_date, start_date);
"""


def migrate(connection: Connection[dict[str, Any]]) -> None:
    """Create the hosted schema and backfill stable prototype coordinates."""
    with connection.transaction():
        with connection.cursor() as cursor:
            for statement in SCHEMA.split(";"):
                if statement.strip():
                    cursor.execute(statement)
            cursor.execute(
                "SELECT id FROM benches WHERE latitude IS NULL OR longitude IS NULL"
            )
            updates = []
            for row in cursor.fetchall():
                number = int(row["id"].removeprefix("Bench"))
                latitude, longitude = generated_bench_coordinates(number)
                updates.append((latitude, longitude, row["id"]))
            if updates:
                cursor.executemany(
                    "UPDATE benches SET latitude = %s, longitude = %s WHERE id = %s",
                    updates,
                )
            cursor.execute(
                """SELECT a.adopter_id, a.bench_id
                   FROM adoptions a
                   WHERE a.is_seeded"""
            )
            seeded_adopters = [
                (
                    generated_adopter_name(
                        int(row["bench_id"].removeprefix("Bench"))
                    ),
                    row["adopter_id"],
                )
                for row in cursor.fetchall()
            ]
            if seeded_adopters:
                cursor.executemany(
                    "UPDATE adopters SET public_name = %s WHERE id = %s",
                    seeded_adopters,
                )
            cursor.execute("ALTER TABLE benches ALTER COLUMN latitude SET NOT NULL")
            cursor.execute("ALTER TABLE benches ALTER COLUMN longitude SET NOT NULL")


def _seed_in_transaction(
    cursor: Cursor[dict[str, Any]], *, randomizer: Random | None = None,
) -> None:
    cursor.execute("SELECT COUNT(*) AS count FROM benches")
    if cursor.fetchone()["count"]:
        return
    benches = []
    for number in range(1, 551):
        latitude, longitude = generated_bench_coordinates(number)
        benches.append(
            (
                f"Bench{number}",
                generated_bench_location(number),
                latitude,
                longitude,
            )
        )
    cursor.executemany(
        "INSERT INTO benches (id, location, latitude, longitude) VALUES (%s, %s, %s, %s)",
        benches,
    )
    today = park_today()
    for number, start, end in generate_initial_adoption_timelines(
        today=today, randomizer=randomizer
    ):
        cursor.execute(
            "INSERT INTO adopters (public_name) VALUES (%s) RETURNING id",
            (generated_adopter_name(number),),
        )
        adopter_id = cursor.fetchone()["id"]
        cursor.execute(
            """INSERT INTO adoptions
               (bench_id, adopter_id, start_date, end_date, amount_cents, is_seeded)
               VALUES (%s, %s, %s, %s, %s, TRUE)""",
            (
                f"Bench{number}", adopter_id, start, end,
                ((end - start).days + 1) * DAILY_ADOPTION_RATE_CENTS,
            ),
        )


def seed(
    connection: Connection[dict[str, Any]], *, randomizer: Random | None = None,
) -> None:
    """Add the initial inventory once; repeat calls do nothing."""
    with connection.transaction():
        with connection.cursor() as cursor:
            cursor.execute("LOCK TABLE benches IN ACCESS EXCLUSIVE MODE")
            _seed_in_transaction(cursor, randomizer=randomizer)


def _initial_adoption_rows(
    cursor: Cursor[dict[str, Any]],
) -> list[dict[str, Any]]:
    cursor.execute(
        """SELECT a.id, a.bench_id, a.adopter_id, p.public_name
           FROM adoptions a
           JOIN adopters p ON p.id = a.adopter_id
           WHERE a.is_seeded
           ORDER BY CAST(substring(a.bench_id FROM '[0-9]+') AS INTEGER)
           FOR UPDATE OF a, p""",
    )
    rows = cursor.fetchall()
    if not rows:
        raise RuntimeError(
            "Expected at least one initial adoption; no records changed."
        )
    return rows


def refresh_timelines(
    connection: Connection[dict[str, Any]], *, randomizer: Random | None = None,
) -> int:
    """Refresh seeded timelines while preserving visitor bookings."""
    with connection.transaction():
        with connection.cursor() as cursor:
            rows = _initial_adoption_rows(cursor)
            timelines = generate_initial_adoption_timelines(
                today=park_today(), randomizer=randomizer, count=len(rows)
            )
            for row, (_, start, end) in zip(rows, timelines, strict=True):
                cursor.execute(
                    "UPDATE adoptions SET start_date = %s, end_date = %s WHERE id = %s",
                    (start, end, row["id"]),
                )
    return len(rows)


def expand_adoptions(
    connection: Connection[dict[str, Any]], *, randomizer: Random | None = None,
) -> int:
    """Add generated bookings until 343 benches are currently adopted."""
    today = park_today()
    with connection.transaction():
        with connection.cursor() as cursor:
            cursor.execute(
                "LOCK TABLE benches, adopters, adoptions IN SHARE ROW EXCLUSIVE MODE"
            )
            cursor.execute(
                """SELECT COUNT(*) AS count
                   FROM benches b
                   WHERE EXISTS (
                       SELECT 1 FROM adoptions a
                       WHERE a.bench_id = b.id AND a.end_date >= %s
                   )""",
                (today,),
            )
            current_count = cursor.fetchone()["count"]
            if current_count > INITIAL_ADOPTION_COUNT:
                raise RuntimeError(
                    f"Already found {current_count} adopted benches, above the "
                    f"{INITIAL_ADOPTION_COUNT}-bench target; no records changed."
                )
            needed = INITIAL_ADOPTION_COUNT - current_count
            if needed == 0:
                return 0
            cursor.execute(
                """SELECT b.id
                   FROM benches b
                   WHERE NOT EXISTS (
                       SELECT 1 FROM adoptions a
                       WHERE a.bench_id = b.id AND a.end_date >= %s
                   )
                   ORDER BY CAST(substring(b.id FROM '[0-9]+') AS INTEGER)
                   LIMIT %s""",
                (today, needed),
            )
            bench_ids = [row["id"] for row in cursor.fetchall()]
            if len(bench_ids) != needed:
                raise RuntimeError(
                    "Not enough available benches to reach the adoption target; "
                    "no records changed."
                )
            timelines = generate_initial_adoption_timelines(
                today=today, randomizer=randomizer, count=needed
            )
            for bench_id, (_, start, end) in zip(bench_ids, timelines, strict=True):
                bench_number = int(bench_id.removeprefix("Bench"))
                cursor.execute(
                    "INSERT INTO adopters (public_name) VALUES (%s) RETURNING id",
                    (generated_adopter_name(bench_number),),
                )
                adopter_id = cursor.fetchone()["id"]
                cursor.execute(
                    """INSERT INTO adoptions
                       (bench_id, adopter_id, start_date, end_date, amount_cents, is_seeded)
                       VALUES (%s, %s, %s, %s, %s, TRUE)""",
                    (bench_id, adopter_id, start, end, 10000),
                )
    return needed


def refresh_locations(connection: Connection[dict[str, Any]]) -> int:
    """Refresh all prototype labels and coordinates without changing bookings."""
    expected_ids = {f"Bench{number}" for number in range(1, 551)}
    updates = []
    for number in range(1, 551):
        latitude, longitude = generated_bench_coordinates(number)
        updates.append(
            (
                generated_bench_location(number),
                latitude,
                longitude,
                f"Bench{number}",
            )
        )
    with connection.transaction():
        with connection.cursor() as cursor:
            cursor.execute("LOCK TABLE benches IN SHARE ROW EXCLUSIVE MODE")
            cursor.execute("SELECT id FROM benches")
            actual_ids = {row["id"] for row in cursor.fetchall()}
            if actual_ids != expected_ids:
                raise RuntimeError(
                    "Expected the complete Bench1 through Bench550 inventory; "
                    "no locations changed."
                )
            cursor.executemany(
                """UPDATE benches
                   SET location = %s, latitude = %s, longitude = %s
                   WHERE id = %s""",
                updates,
            )
    return len(updates)


def normalize_content(connection: Connection[dict[str, Any]]) -> int:
    """Replace legacy placeholder labels without touching visitor-created records."""
    with connection.transaction():
        with connection.cursor() as cursor:
            initial_rows = _initial_adoption_rows(cursor)
            for number in range(1, 551):
                cursor.execute(
                    """UPDATE benches SET location = %s
                       WHERE id = %s AND location LIKE 'Demo Zone %%'""",
                    (
                        generated_bench_location(number),
                        f"Bench{number}",
                    ),
                )
            cursor.executemany(
                "UPDATE adopters SET public_name = %s WHERE id = %s",
                [
                    (
                        generated_adopter_name(
                            int(row["bench_id"].removeprefix("Bench"))
                        ),
                        row["adopter_id"],
                    )
                    for row in initial_rows
                ],
            )
    return 550 + len(initial_rows)


def reset(
    connection: Connection[dict[str, Any]], *, randomizer: Random | None = None,
) -> None:
    """Erase all bookings and restore the initial state atomically."""
    with connection.transaction():
        with connection.cursor() as cursor:
            cursor.execute("LOCK TABLE benches, adopters, adoptions IN ACCESS EXCLUSIVE MODE")
            cursor.execute("DELETE FROM adoptions")
            cursor.execute("DELETE FROM adopters")
            cursor.execute("DELETE FROM benches")
            _seed_in_transaction(cursor, randomizer=randomizer)


def main() -> None:
    """Run a migration, seed, or explicit operator reset."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "command",
        choices=(
            "migrate", "seed", "expand-adoptions", "refresh-timelines",
            "refresh-locations", "normalize-content", "reset",
        ),
    )
    parser.add_argument("--yes", action="store_true", help="Confirm the destructive reset")
    args = parser.parse_args()
    if args.command == "reset" and not args.yes:
        parser.error("reset removes all bookings; pass --yes to confirm")
    database_url = os.environ.get("DATABASE_URL")
    if not database_url:
        parser.error("DATABASE_URL is required")
    with connect(database_url) as connection:
        {
            "migrate": migrate,
            "seed": seed,
            "expand-adoptions": expand_adoptions,
            "refresh-timelines": refresh_timelines,
            "refresh-locations": refresh_locations,
            "normalize-content": normalize_content,
            "reset": reset,
        }[args.command](connection)
    print(f"{args.command} complete")


if __name__ == "__main__":
    main()
